version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: si-app
    container_name: si-app
    restart: unless-stopped
    tty: true
    environment:
      - APP_NAME=SICounsellor
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=si_app
      - DB_USERNAME=root
      - DB_PASSWORD=
    volumes:
      - .:/var/www/html
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:latest
    container_name: laravel-db
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=si_app
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - laravel

networks:
  laravel:
    driver: bridge